apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:SxFSf1cGX6HsKOtQzDFf/dQUKBrGjVLSVwAJSkYaHF7fl7ROvqly4w==,iv:c05DUKnYLlsS3xoJqgZpZGpcLkGXDomMLbmERxPOpDA=,tag:IAK1qODSdPqToAozPpeS+g==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVlgvOVUxSnZUdCs1alVu
        UVQyNkhDdmhvZWllN3Y0SkI5aEhxUjd4ZmhzCjdMbkM3c3JQSkVPOUlTTndUNURM
        Um1nSTIzMzhYaUZlYXg5cmFFQXpsT1EKLS0tIHBNS0VEUExqTXdyYXU3bGUybGlN
        WE5JRE0wYUl6UHhIc09TaHVSZmFsUGMKRkT5dA5875OfqkChUYGyGf0KQEl7QdAx
        XCK38AHvGFNgO/7aWfdLeNN1x/+x9ISUgvGC04YsxwGiUITVi3L33Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T22:26:06Z"
  mac: ENC[AES256_GCM,data:k0I8A/sd7gla/0hgAMSCNTXj6qc3RZsU9W6ax9bMu9Wo0VO//4CyvV7hHlmWe6LpenD/tHCVaTigTYz3t08O765c5n3zAr4zH8BG0GtgLsIa2vzb9cm7ZblsAN6wcelN3D6RFCiZypsXCeslM7tWwwkKuQ70/HBb2e5Gzyaq/xc=,iv:uaxiBvgzjNImSMkC4eqGKZft66C38ejjcGdGtBp0zY8=,tag:0qcq4syChAUHByx0GKuIpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
