apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:AM8XvOKGFMcOY4oTCAqQwf4C1o7t2IWCefRvlaplf0ueH5QuEi/X0Q==,iv:T4m9R6E5RUjJ7s1EpvKQb08NJW3kvHfQUmQjlZbcH2I=,tag:knLOmzini0NwWHFQL8saeQ==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU2NmcHUxOWszNStVdXly
        UWdtZWlBYWdyRHh5dVB5Q01Xa2g5b1VCVFJnCitqbjJGZU1XYnpERTdVZ0E4Y3VD
        VDFVZkVWdUUwcW05blJjOXlhMXhRTmMKLS0tIHZCa084V2tUWVZ1ZXVlY0gyRjM1
        YWVqcGFnVmdYUHRibUJiUzZPM3lBcncKPVP4QNY4Xk+9HiVpLxz4lBz592RNLhKx
        8l3q2UXZlmuC35R4mmi6C8AmanA0hxRmQUhkAP7WYqU12OFjZIgHdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T00:07:15Z"
  mac: ENC[AES256_GCM,data:Ed39A4YJ0lGsk2PqtzUEJg9KnPNNhNE7iIDOymaysID0YrhwnUk++HhI/slcbQFpsLZ0BRV/oSowVLkBVMbGMn8cM2nHW1BBMkBmQ8LSgoPqiJkGMePmYfKegGxVPMguQwPcG1MSXh1Zcw6+AsqIBJ1DhWXFFCjSiL8jr9qSf5Y=,iv:UqhqCbrBPILk1eZy0ug6X4lPYKAmwvtV7L32dd7DX0U=,tag:9bIhVf9fhW53f9DGK8Duiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
