apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:bBeDoZSFeyfw8y5VaDiA,iv:Gnvrerp1383KWp6Uo4Y7EQULrQHw3+jyHlsUU7MNj6I=,tag:2rIFHBlHJ/libNDsUhO9pw==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bHAyVFNuWmRhR21kR2VU
        WThOOFppaitld0FPS3cyVWVwQ2FVZ1BKdkFRCjlYVVJVRzlkcFg0NENscE05V1Zv
        emFoV05TeE9wczA3aWpqNXlQQlhROHcKLS0tIGNZZW91OVk5c1lhVXdHYi9nZEdr
        bFBhdU9kRFZXUURzTHAyOUVaRDhCYlkKIhAj0DchalaeA1IdxhsYJHLs92XZ496J
        4ubfNnipshSppc7oItSTaCtfxTGVv+4GAhvZEYoFJSjfIAdVMR+95g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T00:07:15Z"
  mac: ENC[AES256_GCM,data:7LIvgBxmEkXoGQ4y0fKUCr/x3Q1oBtDFGKt5npFHbBHg/JLUmZW0tkoOFbaZH1MQFVsRPsoQk/FDjr5XMxTiVfcAv+mEGcdKVM/JgC1IG+05BFEo0rSom24ttgIDta7KP27WiNAa/+TfX+sOXQe5ln3X9rO6zvdyTYJKOqiFCWE=,iv:p8dujLlXyAvs5FwWd8X5ci6SqpKepRsTgWaSoVsJFeI=,tag:eRKVFANCm9/K6xey5xR3Pg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
