apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:t8nToKpRbk/Q3WnN6InF,iv:bL9nFfk9jMwnETRWRNK30EFpA7oZpZGXJFjAxz/D5lc=,tag:6Z33kcrCKei71Gf2DjmVBw==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ckNaUXgvS0xoZXovbVlo
        YnVUQ2hEQnBiZHQ4VlBmZ2Fpdi9jWUF3S3c4CjdCbEc1Zm1PVDNxdTE3amFvL25q
        Yi8ySkJia0E0VjhKUHFVc2p3VGU3U2MKLS0tIGJxbGVWLzM3a3NnVFFyMm8vbjRq
        NCtGNThHM1BPUUs1bzQyMWVhbGdrVWsK1U8nqWBoaLVhAbbR4DARed5Ec5BAUxE5
        khS4h6A9dyJXoH1f7zrQev1i66H2dueyI0NqrMDV3u2ogLN06O2aQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T22:26:06Z"
  mac: ENC[AES256_GCM,data:T3LYgFE8SSEMhlGyL/zJgGALZZKQoEx6YXzLjPnnL9Cx1xAz9DezOoGZjW+qDjWA6gV47ein4vmc42ocUknGz9qTJniugKisAQjI3OuDvdIBcxPnFe3Hms/VznBtIJsgmJtzZX6jCwcWyaRjz5YQ5VxA0EzpEASO2SJBgpaWbXg=,iv:oIE6GNi3QRlc/9aN3qT9RoShyAXJCbSdKntE50viGoc=,tag:ZXTknIP4yB+aO9qAq8DLbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
