apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:g/xwHsMmHaMHwknx+eoI+IwaA+8HwXJC6RvE2FWrn2p6QhOmfyJwOCV7iPwtifCdA4dVqPntYfqJT7J2BLyUyA==,iv:0Kd32bX+pPrutcF/zIphXWJnUQ3iG7GSvTmBf4eHZ5s=,tag:eqCMEAQLVrzZyXma1htoXg==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:Su5Ktktj+KRQPSuqVtlvth5Hx77qmhMj7Hx9ZVroM6ZLU3hPifDFz4lXAo/QT/vhs7s3TtMpGcpMvKqAlzgE8g==,iv:cyQIX656HKNUbk1YFm6WFr7XPdcclyokfMrMMpNyGHU=,tag:GsoER0Z/bBycNH8m65S5LA==,type:str]
  STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:3aJLOmU8ROiYiQJTZCJy17/pbu7ciD+c5Dqc9U1Vl4CLOr6zpfv3uccAzfYsl5CpXGgP0G1HX2vLH+jKH/htSg==,iv:TJnNeoWtju/thJluoWgPcVq4+pD8jhUDFXGsw+9zwyw=,tag:v4OXRYNcLGyL/IzYI+iROQ==,type:str]
  HEADLAMP_OIDC_SECRET: ENC[AES256_GCM,data:06FFTwK5NtSVv9WB25I+/9yfH6JVNL8/Ki3sBgQn3PDJ3YF2UU91t+gAUgOlscyVkQyQqNfi+Qbhj5MVkoOzEQ==,iv:xl02TkCy9hg0U2NpdD3USoMAFep3sNJGUaLvMFRpLf0=,tag:V4J8DH6JUT4aGrJAhMlEFQ==,type:str]
  OIDC_HMAC_SECRET: ENC[AES256_GCM,data:30uQTtBjJfkCfnT/I+jnFgxpgULqq33uzX2tnoWDh7REXMzBt5KZZ9Dkv9W277/6bMkht6pQMWkCQhSmeiGtUQ==,iv:WKxswmCLHHw2pmEvuhLi7GyH30XMVeBTs+8KJxaitdI=,tag:krEF+K/00mJrSjvjAk/jbQ==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMGF3NlRScy9VZktKRWY0
        Z09PbEJPLzJlVXNsR1d1bDN2VlFaQ2tiWXpvCjdNSzVLdFFYbmNlOU1pN1RQd2J2
        Qzk2QnZhMDJ0M05OMmpLWFlKYks0cEUKLS0tIGVtOGF4TTRkVzlyY1VId0JMNzMv
        dUtoVHZsaDEyL0FRNjNGTWVYdkVwclEKZgYglaNr666gSluEaaf9o6ZK4njZIYo4
        1hNeSKc6DGLUf4NON977BQXv33BsOM8cVdRuIh8H5kSU8OvtPjO7yA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T14:33:38Z"
  mac: ENC[AES256_GCM,data:c7p94m+NLdXi/LUWiK/KM7oLrcnS01CAZMMYVB7wADqKu5rE6YGGgrCckfx3KxVBSd2pcJ6xFoizWr8i9Zck+I6H/LVTrSW079JqQaE0lXgmIBdHAIkrbDkPI8pdzxiwPmcIYIhoop3c+jLU2xaKot8fhTY77pcjjtghaJQmlWM=,iv:IndfzgTs7XcjK3HLPkHk1p3FN8akzaKg2WNeY81o+nE=,tag:hUCcTOVpmm+DNAcxlvgCZA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
stringData:
  users.yaml: ENC[AES256_GCM,data:wAtaPSXjhftsHFiJr2Rd4wuyDzqFb/0bUvumh540mUqN9YnVJw3d4ruZakuyS8NPb2efbcocmuykaNMjJKN79532HCJw3VOjEjFMMcLqDaybJmIy5XjLTGfp4/0/m3RqX2J8meNPkcAqxfHgRX6D0cTT4CHlKsbtpCld1c8f6ejpmYpY2zjhJEML1csFO2AW8cikP2EONkHYmrs9Tpf7lwfjn/PPLulJhWr2RxfbATiZmq2OKVdv4gvBmP7Ax5HyVJZLskCM0xVjgjqiAeSiHDIkHCO+G5UUjoyQDHK6wGI2ENmU,iv:X7CA37kNHVscIBbF6NZcUVs6kLqjYHME66FF12lWNgs=,tag:kF2xMfG+x1KlbVjBmxK3kw==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMGF3NlRScy9VZktKRWY0
        Z09PbEJPLzJlVXNsR1d1bDN2VlFaQ2tiWXpvCjdNSzVLdFFYbmNlOU1pN1RQd2J2
        Qzk2QnZhMDJ0M05OMmpLWFlKYks0cEUKLS0tIGVtOGF4TTRkVzlyY1VId0JMNzMv
        dUtoVHZsaDEyL0FRNjNGTWVYdkVwclEKZgYglaNr666gSluEaaf9o6ZK4njZIYo4
        1hNeSKc6DGLUf4NON977BQXv33BsOM8cVdRuIh8H5kSU8OvtPjO7yA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T14:33:38Z"
  mac: ENC[AES256_GCM,data:c7p94m+NLdXi/LUWiK/KM7oLrcnS01CAZMMYVB7wADqKu5rE6YGGgrCckfx3KxVBSd2pcJ6xFoizWr8i9Zck+I6H/LVTrSW079JqQaE0lXgmIBdHAIkrbDkPI8pdzxiwPmcIYIhoop3c+jLU2xaKot8fhTY77pcjjtghaJQmlWM=,iv:IndfzgTs7XcjK3HLPkHk1p3FN8akzaKg2WNeY81o+nE=,tag:hUCcTOVpmm+DNAcxlvgCZA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
