apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
stringData:
  users.yaml: ENC[AES256_GCM,data:QbpALz+unINBRDIretMCP7D3d+1Wt7wur3bowou8uOSINSi/huXTYLq5reIchvtimtkLRMA/5Gc8tSVsptQ6Em3vDxaDXyRvEest2NGvgTxleunbd7sO1aWqEEqrXIloObw0zHuNpqG+m3asXdiFMMgHHwQ7l/GBNDctplgT4gJsS/shtaek3UsYmizSN4wDx1n1sstgXg4bc8gLwNugydRK5rCPKDzj2sNtwUewgOHhg2xA4W3QiXSoB6GvqgqhslLG6I5qeTPM+AFWYV+n+BHtfjOV8m9EWFGUCb+494D275KC,iv:9v6S5ja4de9hDDcoN8dCAlTRrkIhNNxCQyMzK+RPTDY=,tag:ZIPktEtcskOCUBu8c3DN0g==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRGdlUXExRXE0ZmNCazE1
        RmhVYTA1QkpaeDZBYms4MlZRMm1LQ2lmSnl3CjVHSHMzVHdmTExXL1ptc0E3OVNT
        Vi9ycVA5aTF2V2pzMnBNY1N5Tlp1TTAKLS0tIHVyM2ZpbFh5dFlCNVlHR293LzBQ
        N05LbjZNcWZhUUZVYXVpb3dQZ1YyVTQKM/S4nL/mfDh69Ii3u+18C/jkpoegWZVG
        GmAU3pufKtU2TJThSdcBzzvaQBeDDGg2gfySmPLssXL0Wuu+PXuOGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T14:45:57Z"
  mac: ENC[AES256_GCM,data:hoUBOjMqfcwORcdD+g6RmzZmGQaCV3HCzv7qm174KszTnfe57xWVfEdm/vpO/xcpam3RiHj7jNUtlQNaFCfNu7RE4yd68ZyUmUacwaaeTqYYGBeW2OlbPwurIrExAZ3sc3rbZx6oqPwMvspa4Ht6NcGxGtZSacd02L+INhpNJV8=,iv:bcmABTfR7r092zkAlYe00KmUOUpP4cAfJXpoEUMxLSY=,tag:1TTx7MgPjM1hiOlrGMUnTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
