apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:utzjYVqXkqpl/pHW1rOlH/QrgMnEpjmzPVsMxkuKQSc=,iv:nNEo6sxAttOlcS1f8iV3qRhDE1/uJ3Z1qjKHvVgGUi4=,tag:YD/3frHfo6Nbm0hG1iN1nQ==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNnlGdUFjUEZTNGt5NjdX
        VFJ2Zk9NanA0dWVSODUxR3ppVkhzVWhyQm5RCnZLUFpuUUxVV0FYWTk2UnlJTHNq
        WlFqS3NpNDZ4YUROYUJuR1dBdFlFVjgKLS0tIHhDcTlZd2ZVYXNuYlFDRm1ZcVhH
        T09XL2RSaWJIeGMzTVBkdUdSclpDMDQK0WZXeGXFgYglbR6ig9tMG6ulZYsh1pFx
        EXtnydq7Qu/WZJ2zwZ/x9EkoUV3uB3N9ocMbRihhkmSbq3PGpF1HGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T22:26:06Z"
  mac: ENC[AES256_GCM,data:1URzquNjsSJa4AQ/6iHcTcPmBoYTq9zw2d+g0N8egoR27X6IOeXuxAdZl+KwRcVZGzfrL4ANW166wj+RJ04c76G1MB79kHAqvGMy1xYyEPRLrwNLfoyqJ3rVafgkSkZwW27KJW0jbnVFcZNqGyo+XatI69BTXcq9vxXJ9HPjRn4=,iv:rlPUTObgUpSTxlKw1hc0oH7tAQHRU9AkmD6RMVK8R50=,tag:gKkIkm4FQ/Fe8npqpOzIGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
