apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:HShNFP5Ze6gm7iNf3Zwo7HkbOavx+o3t/ZBwfmAQd/o=,iv:dhxPdU6W5S5MsTIRxq/JVNQXCLGZ3VQdoQbOWhfm4dI=,tag:tOlEk6kN1ImUNXi3UFTPAg==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRkdVT3hINFh0N285NElO
        aUZXUVljNFRSLzlFbllwZjZMZzFPNGRsaEVBCjR0eWQ1SDZXYml2S3N4Ukw1YzBM
        MjdTR0JaMzl0V2traTJBUFcwbTZoelUKLS0tIGxYOElsL0xkNVlaYVBjTlZ1M0NV
        bHdvcXVvTDFhRXFSTXl1NGQyOTVCWnMK9cop4sRetrEhu61zOTkLutgVmG4KuzAd
        3YRUJpupbbkfMOy7h859iCY5LynywzmYdCFiNxvCDH3Ww+c8QarbtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T00:07:15Z"
  mac: ENC[AES256_GCM,data:ivG0w7UeQNqDZQroHk618ewKt5wXL6fldhxcOCrtu77G8SfUj7dWperM3HaFbfytOzbjWHLIAiZSbLIHtqmHBNkNmbc2khjxP+Fr9Ax/h2KDhuKROSs305rv+pgbPBI3zwngWPlpkL/9CRjEi4n8/WesL3VW+kojOWort6VlwLE=,iv:vKOeW4zsSYBWFFGPfR/VOhc8mcuaL1W7AYjNgIzaoGA=,tag:VDCrKgCMzbhoqcHOi5+fLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
