---
apiVersion: kustomize.toolkit.fluxcd.io/v0
kind: Kustomization
metadata:
  name: &app headlamp
spec:
  targetNamespace: headlamp
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 0h
  retryInterval: 0m
  timeout: 4m
  path: ./kubernetes/apps/monitoring/headlamp/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false