apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1xd/Hh/24MRqyi+411xyC9MPBhDN85X4Atysj88c/ARSbM25ZYr5gzcTbAgshEwLSFr+DdK/Q4jTyo7PPFyWq9A7a9Wusr0QY8cTIX+FVLT11AO6ajvsoJZjbgOW3IfgRym8NZdCwpScyGiPjPddehf/jjEO//LNExC2yIq2Sxii0lnj7yc1c2ho5FRDMyzRKqEgY4+f+7J+y1SF5Was8ckBzUxhsK3VMw4DQAK2dy0v6A9G,iv:Tqb/DHf8wS8+lc9vDubNf/h0aqtZ5qKkQy2c7ARrXgo=,tag:cGgC7yay0bhwPlBOFccMmw==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRXlXOTRHeHNTaG1VNVdZ
        V3l5TlkvZWMzd2x1SmVwb3lyZ0V2S3Q4V0RBCk95TERuNmVoQTZpTEZYYWdVdlYz
        RDZlcXpXY3V2YTMzSnBPUllBdHgwdUEKLS0tIFNFZjdqKzZCbUtBa3A5ZHlYNExi
        emZOYmxPRnJnUVJFaXI1b3lFbi85ZHcKOjXlXH0Ee9fWpTluglmAWwf3JrxEwTxM
        8lgFOKi+BFhy0k44BJ5bZdrOAB5zR2ztlM4YOKHTX2IL5Dhwy+nr0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T22:26:06Z"
  mac: ENC[AES256_GCM,data:9RTpJa+bcUScUg/tAKoQT/k9GKz8Da0Egc4zyAjKdL2pHI4lQccFiSvYFakNL7I7TdmAe5FvU8hEEBXpz57mVTMlmVIFs9uy8z28pMnuqOpbvrc1ers2h4zE6s4elOya/HNubU7QOSgUIdpc/FVA/u2FUzea70UKOLr6SanYKKY=,iv:EmJiriUmz21GMmcrSbOxZHuPljDOlaVCzg/lfKE3k1U=,tag:cxpdrAxyuJpNjqvrxVlFOw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
