apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:rx+HE4+ThXHhpUq0lYkqJQCUimohUiue/s5W/J97rdliAsJg0Ww+RjcFI1DnjGLDVuhXH+P59+wcJqPP35XkCvhxiFxEsuYZclRUfFvCWUnnzYf1PTr4U4sxjlIkChRb4s9u7ncSi8h8ipehrT+yHNXdZ1F3cfNSYalTLFDzD7uz+WqGTfOOEpaxCAdcV4NzNzHpbMJFxnUMatbMU9KKXEdNBGxtXv7px9EBDHcy68gv9YJB,iv:ybqe0RtLovmZkiTS07YRae/14DhPwYk8Q9eAnB2uWMc=,tag:4rdP9ZKx6QudOfZ/DaCovg==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaDdHOFJSYS9UVTkzbGp3
        ZG90OVpzcG5Oc1dpUTZHN3pMSDZmbWNpUWhvCk5qcjdiclBKUFFJREhCcEkrbXhp
        LzhMZnJxZVhmY3FONWNIaXpzVlZYcEEKLS0tIFhLanhiS3F2Tm5sNzNFT0VPaUN0
        ZkVSWkIzM3g0Q1V5VGVISzRJM2NUZFkKuEDv+aE3YvqHJ2dPLVrNrQXUDiWpjx4s
        s5lrYFQw9bezwScKgCcTcZHgcXmC3TvpwatA0/MW9gePgEgP5L4p4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T00:07:15Z"
  mac: ENC[AES256_GCM,data:mhnLUU2PaVHgQ4ws/vhPbfLVaj9Mh9SKtqaMNtbQQsn0Aslbr+AzpbIWVgSbyZoYhBRrZvM7BKObqIujSoBpeM93ngLg1aRR5ApOPr+b5CzulqBCHmEM4ubnpf9FF6Qn9B6AThJ8I44lQ4PeINwCoSurfbpiRGSgbGyNgIcnps4=,iv:qjziKt84jiRWUEE6JGOBR29UvCbBDKaPlgw82xsQ2Fg=,tag:lJloCF0emo6eWA/Nvv+B+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
