apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:eHf/9mTrwADasaLnf5V54xq5xguF5TD/StdtMw4EXJyR3yImf2KPyg==,iv:+PPBeGF/2cUJj/oi80RTtzPEmZltyOxbL1b+PjGllbU=,tag:4OJzMsimfMp8AY8iIMWMOg==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsajVtL3pNb2hSakNCL0VM
        YlJCTjZadnRpU3R1NE54N3pZU0prVE8yd21rCjlZa3hxZTVTWkVlekg1Rm1WYnFh
        RUpqSEFCdzZ4L00vUkNPVDlDaEFkeUkKLS0tIDlaWlZlbkU2Uzc5VkF2SmhuQUJS
        ZlA4Q1VSQTN0MmxPR1NkSnpEblYralkK6aBBUjBfgYcJb8afILo3B9JlyCrUiVr9
        SCY6BQFhfTf7bCgFug92Q/oA+VcAbcuh7iDTr8cs3W/0iiuQNbkR+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T00:07:15Z"
  mac: ENC[AES256_GCM,data:9ha/P/Au5WaIRHKU6X7Hfc82nIMthN+mLOK5FNTYdDqb1iVwVIaKMAByfE10KOQWWrdl54YdOK6cnII8IJCbFjSUGxdQAHP9zTRqY7hytRXUNXtjZqCyZ6ZBvObVQle2dbf2H1NhxFH2/QjRMJFGIfjwmoTRywUI+oZg1EgK5S0=,iv:gmHEjB6N5xlV90LCWBZMsYH3mDIbd6pyn3MVh+uGlA0=,tag:wEQcpOvyX7Foe6KZwqR38Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
