apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:59nnCL805MG5u6D7zTZzRHbucf/A9eSWeYExCXlM7oz+82qUiEisyQ==,iv:Gv3Pq2r+/AvPmu/z6yKmbxq8eVnXIdjhO4GHUXL0KAU=,tag:m9WafP18C+KwIAc88YuHXg==,type:str]
sops:
  age:
    - recipient: age1n2awjm6y37jq8aejmmudpq8sa4ymdcd2vq5d9tag2887gn3lramqkfgqf0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcEY1ZXRoMElqNUNFcnE4
        UnI2UGw4M0F3UXYyNy85SllpM2Q1TGFJekNBCjkvVFBjMUdHV2g3aFdxWkU2V1Ez
        ZG80elk5US92T2gyVDA1dTlSTU96UnMKLS0tIDFGWTFiQkpicnNQU2pJaHpKRmhm
        YjBFQlNXejBKUGtORjBBU2JnclRTaUEKLXCvZmhlPQ9YhnMGXMuh8RXQLVEEJUni
        JPzGx06PVMykhxTGIroaMLRqvZshqzVcXjYGdVgcS0Y+kd54LU5b3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-16T22:26:06Z"
  mac: ENC[AES256_GCM,data:Vb5cOdb5sWBc3gaPoWGGyvisBAcbZodZiOrfdWzbS9FjSLMfMoY+De+ZjzBX8lC4OuhijoJKZw88hQ7ImQwsc8kcNPxd2ycEHeFeGQqLu7XeOvnZjwz0ntS2qsqqJWIzC+naj/VjJxLcT8W8Pgcwqbd2/sMmorcqLZib41UQXjE=,iv:NalCeTFtGi1x4pw0utu6W1hQ53D/7oOjFJn63ML7PIg=,tag:/PQxKolMAlisgMVr0SmMww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
